/*
-- Query: SELECT * FROM hms.service
-- Date: 2021-02-28 12:17
*/
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (1,'Nhu cầu chăm sóc, làm đẹp của chị em không hề giảm khi đi du lịch hay công tác, do đó các dịch vụ Spa đang ngày càng được du khách phản hồi nồng nhiệt,Bao gồm: xông hơi, lột mụn, gội đầu ...','Spa','lần',500000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (2,'Các phòng tập thể dục đa năng hay các phòng tập gym luôn là nơi được du khách quan tâm. Khi đi công tác hay du lịch nhưng nhiều người vẫn muốn đảm bảo tiến độ tập luyện cho cơ thể mình. Đây là lí do các phòng tập gym ra đời và ngày càng mở rộng.','Gyms','buổi',50000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (3,'Dịch vụ sân golf và sân tennis chỉ dành cho các khách sạn cao cấp. Vì đây là các môn thể thao dành cho giới thượng. Bạn sẽ bắt gặp các sân golf với diện tích lớn tích hợp trong các khu khách sạn, nghỉ dưỡng, biệt thự cao cấp.','Tennis','giờ',100000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (4,'Bắt nhịp với xu hướng hiện đại, kinh doanh khách sạn ngày nay không chỉ đơn giản là phục vụ nhu cầu lưu trú và ăn uống như trước, mà ngày nay các chủ đầu tư còn tập trung phát triển các dịch vụ vui chơi – giải trí, trong đó có dịch vụ cafe.','Cafe','lần',200000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (5,'Đây là một trong những dịch vụ thường thấy ở các khách sạn. Dịch vụ xe đưa đón nhằm đáp ứng nhu cầu di chuyển ngày càng cao và mong muốn tạo được trải nghiệm thoải mái nhất cho khách hàng.','Xe đưa đón','chuyến',450000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (6,'Thuê xe ô tô gần đây đã trở thành một lựa chọn thoải mái và an toàn cho các chuyến đi chơi. Loại hình di chuyển này cho phép bạn khám phá nhiều địa điểm du lịch cũng như chủ động hơn trong việc sắp xếp lịch trình tham quan. Ngoài ra, chi phí thuê xe cũng được cân nhắc là rẻ hơn các phương tiện khác khi du lịch cùng gia đình hay bạn bè. Dưới đây là một số điều bạn cần chú ý khi chọn xe thuê và tiến hành thanh toán để có một trải nghiệm an toàn và thoải mái khi đi du lịch.','Thuê xe tự lai','lần',500000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (7,'Hãy thư giãn tại khu vực quầy Bar của chúng tôi và khám phá các dòng rượu vang và champage đặc biệt có những sự lựa chọn độc đáo và phù hợp với từng thời điểm','Bar','lần',300000);
INSERT INTO `service` (`service_id`,`description`,`service_name`,`unit`,`unit_price`) VALUES (8,'Với nhiều món ăn khác nhau Quý khách có sự lựa chọn đa dạng về các loại bánh mỳ và bánh ngọt trong bữa sáng, có nhiều loại phô mai, thịt nguội, sữa chua, salad hoa quả và nước ép trái cây. Chúng tôi còn có nhiều sự chọn về các loại ngũ cốc, trứng, mứt, mật ong.... Quý khách hãy đặt phòng trực tuyến để có bữa sáng miễn phí tại khách sạn của chúng tôi.','Ăn sáng','bữa',100000);
